org:
  ogier:
    modules: api, resource, service, persistence, gateways, test, parent, async, exe
    mandatorymodules : parent, exe
    nonbusinessmodules: exe, api, async, test
    excludesubmodules: exe, api, async, parent